services:
  app:
    depends_on:
      mysql:
        condition: service_healthy 
    container_name: nest_app
    restart: always
    entrypoint: 'npm run start:debug' 
    env_file: ./.env
    volumes:
      - .:/usr/src/app  
      - /usr/src/app/node_modules 
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '${API_PORT}:${API_PORT}'
      - '9229:9229' 
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_SYNCHRONIZE: true
    networks:
      - nest_app_network

  mysql:
    image: mysql:8.0
    container_name: nest_app_mysql
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SYNCHRONIZE: true
    ports:
      - "3307:${MYSQL_PORT}"
    networks:
      - nest_app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  nest_app_network:
    driver: bridge
